### DISCUSSION TITLE
Using diyhue on Synology NAS

### DISCUSSION THREAD

**Discussion by Mr-Groch** [diyhue/diyHue#797] [Show and tell]
Hi!

I've managed to get it working on Synology NAS as docker container on macvlan network! Bellow you can see my docker-compose.yml.

My LAN network is 192.168.1.0/24, DHCP starts from 192.168.1.100, so I decidec to use 192.168.1.64 for diyhue container. On my NAS there is also MQTT and HA containers, so there is need to access it from diyhue - I created second bridge network to get access to other containers from diyhue (diyhue see's other containers exposed ports on 172.18.0.1).

Secret is that name of macvlan network should be lexical before bridge network!! Docker will set default route to first network alphabetical

Beyond that macvlan needs to have highest priority to obtain desired mac address...

```yaml
version: '3.8'
services:
  diyhue:
    image: diyhue/core
    container_name: diyhue
    restart: unless-stopped
    volumes:
      - ./:/opt/hue-emulator/config
    environment:
      - MAC=02:42:c0:a8:84:64
      - IP=192.168.1.64
    mac_address: 02:42:c0:a8:84:64
    networks:
      10_vlan:
        priority: 100
      20_internal: ~

networks:
  10_vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.64/32
  20_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/30
          gateway: 172.18.0.1
```

**Comment by zwenty** [comment]
Hi!

I'm desperately trying to get this work. No luck so far. I'd like to see my Home Assistant lights in diyHue.

I got Home Assistant running on Docker on my DS and access it via my DS ip port 8123.

I changed your docker-compose with my network settings and the DS mac address.

btw: why do you mount
` - ./:/opt/hue-emulator/export`
instead of:
` - ./:/opt/hue-emulator/config`

When I run the compose I do get the following error:

`ERROR: for diyhue  Cannot start service diyhue: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2022-04-12T23:10:27+02:00" level=fatal msg="failed to add interface dockercadfed9 to sandbox: failed to set link up: device or resource busy": unknown`

So I did leave the vlan in portainer and started the container: success

Next I deleted the vlan and set up a new one in portainer with same network settings but different name.
I joined the new macvlan with the diyhue container and voila: container is running

So now I'm able to access diyHue UI via the macvlan ip address: nice

Next I did configure the Home Assistant settings in the diyHue UI
`IP: DS IP address
| port: 8123
| token | include by default`

Unfortunately this did not do the trick, no lights showed up.

I checked the logs and found that diyHue is not connecting to Home Assistant.

`2022-04-12 23:05:19,929 - services.homeAssistantWS - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
2022-04-12 23:05:22,937 - services.homeAssistantWS - ERROR - Error connecting to Home Assistant WebSocket
Traceback (most recent call last):
  File "/opt/hue-emulator/services/homeAssistantWS.py", line 234, in create_websocket_client
    homeassistant_ws_client.connect()
  File "/usr/local/lib/python3.9/dist-packages/ws4py/client/__init__.py", line 217, in connect
    self.sock.connect(self.bind_addr)
OSError: [Errno 113] No route to host
Starting remote discovery`

Now I'm kinda lost... 

Any clue why diyHue doesn't connect to HA?

**Reply by Mr-Groch** [reply]
Hi! First `- ./:/opt/hue-emulator/export` instead of `- ./:/opt/hue-emulator/config` because when I wrote this export dir and json config were in satble branch - new config were only on beta branch... It needs to be changed for currentversion...

Second - I'm not using portainer and that compose file is working for Synology Out-of-the-box docker instalation. Portainer is managing docker networks on its own, and I'm not suprised that isn't working...

I can't help with portainer...

Macvlan docker networks are seperated from host network, so the trick is to join second bridge network for diyHue container and you can then access host from that bridge gateway IP. Container primary network must be macvlan for multicast to work - docker engine will set default route to first network alphabeticaly - macvlan network name must be lexicaly before bridge network name!

Other thing - MAC used in diyHue config must be not Synology LAN MAC, but macvlan adapter MAC - you can generate your own MAC for this...

**Reply by zwenty** [reply]
Thanks for getting back :-)

I did run the compose in CLI on my DS, from directory /volume1/docker, not from inside portainer. Then I got the error.

Can I find out where on the way between the diyHue container and Home Assisstant the route is blocked?

About the MAC:
So I can basically use any MAC which is not used in my network in the compose? Or how do I find out the macvlan adapter MAC?

**Reply by Mr-Groch** [reply]
It can be many things... 

`eth0` here you should change to network interface name of your Synology LAN port
```yml
    driver_opts:
      parent: eth0
```

`subnet` should be your LAN subnet where Synology is connected to
`gateway` should be your LAN gateway (router IP) where Synology is connected to
`ip_range` IP here should not be used in your network by any host
```yaml
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.64/32
```

And for biridge network - `subnet` and `gateway` should not be used by any other docker network...
```yaml
      config:
        - subnet: 172.18.0.0/30
          gateway: 172.18.0.1
```

For macvlan MAC address you can choose any not used MAC on your network
