### ISSUE TITLE
Support of ZBMini

### ISSUE THREAD

**Issue by eporsche** [diyhue/diyHue#1000]
I have a question regarding smart switches like the ZBmini and iCasa. Those are published via zigbee2mqtt to another topic than /homeassistant .  Instead they are published to zigbee2mqtt/FRIENDLY_NAME/set
(https://www.zigbee2mqtt.io/devices/ZBMINI.html)

Is there a way I can add those to diyhue, too? Other than running and connecting my old HueBridge. I tried to connect to emulated hue of home assistant, but this didnt work.

**Comment by eporsche** [comment]
Can be close - 
The homeassistant integration did the trick - in compination with a light template entity for the switch:

```yml

light:
  - platform: template
    lights:
      lamp_light:
        friendly_name: "Lamp"
        turn_on:
          service: switch.turn_on
          entity_id: switch.lamp
        turn_off:
          service: switch.turn_off
          entity_id: switch.lamp

```
