### ISSUE TITLE
points_capable error when connecting Hue app

### ISSUE THREAD

**Issue by enoordam** [diyhue/diyHue#1062]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

I have a Phillips Play Gradient lightstrip I am trying to connect using diyHue. I connected it successfully in Home Assistant, and have added it to diyHue as well.

I open the Hue app and got it to connect to the bridge, but then it gets stuck and diyHue starts generating a lot of errors:

2025-01-01 20:53:33,547 - werkzeug - 225 - INFO - 192.168.1.112 - - [01/Jan/2025 20:53:33] "GET /clip/v2/resource HTTP/1.1" 500 -
2025-01-01 20:53:33,673 - werkzeug - 225 - INFO - 192.168.1.32 - - [01/Jan/2025 20:53:33] "GET /api/ff5c153ec8c311ef88361c697a63c8d8/groups/0 HTTP/1.1" 200 -
2025-01-01 20:53:33,676 - werkzeug - 225 - INFO - 192.168.1.32 - - [01/Jan/2025 20:53:33] "GET /api/ff5c153ec8c311ef88361c697a63c8d8/config/swupdate2 HTTP/1.1" 200 -
2025-01-01 20:53:34,494 - werkzeug - 225 - INFO - 192.168.1.112 - - [01/Jan/2025 20:53:34] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
2025-01-01 20:53:34,520 - werkzeug - 225 - INFO - 192.168.1.112 - - [01/Jan/2025 20:53:34] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
[2025-01-01 20:53:34,544] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 274, in get
    data.append(light.getV2Api())
                ^^^^^^^^^^^^^^^^
  File "/opt/hue-emulator/HueObjects/Light.py", line 292, in getV2Api
    "points_capable": self.protocol_cfg["points_capable"]}
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'points_capable'


### Errorlog:

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Log tar
This is also included in Full debug
If diyHue does not start upload from normal log
```


### Steps to reproduce

Open Hue app and try to connect.

### Please enter your operating system details here

If diyHue does not star use "uname -mrs"
Hue-Emulator Version: 2024-12-17 13:34:18.000000000 -0800
WebUI Version: 2024-12-01 02:25:10.000000000 -0800
Architecture: x86_64
OS: Linux
Linux version: #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec 5 13:09:44 UTC 2024
Linux release: 6.8.0-51-generic
Hardware: %Hardware%


### Upload debug tar

[config_debug_2.zip](https://github.com/user-attachments/files/18287963/config_debug_2.zip)


### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
https://diyhue.readthedocs.io/en/latest/lights/lightTypes.html https://github.com/diyhue/diyHue/issues/1037 https://github.com/diyhue/diyHue/issues/1035 https://github.com/diyhue/diyHue/issues/1014

**Comment by enoordam** [comment]
Thank you, I missed the solution there. I tried your suggestion to switch to LST002 per #1035, but something isn't quite right.

The Hue app sees it, and I can do basic control, that works well. However, any kind of effect from either the Candle/Fireplace effects in the Hue app or an entertainment/sync effect in Hue Essentials on my TV only set one color, and not always one that seems correct, with no motion.

**Comment by hendriksen-mark** [comment]
that is true, you have not added your light good.
```
'1':
  id_v2: eeaf3ab9-2562-4328-a208-f15871c76fd7
  name: TV Ambient Lighting
  modelid: LCX002
  uniqueid: 00:17:88:01:00:87:3a:7a-0b
  function: mixed
  state:
    'on': false
    bri: 254
    hue: 8417
    sat: 140
    effect: none
    xy:
    - 0.0
    - 0.0
    ct: 366
    alert: select
    colormode: ct
    mode: homeautomation
    reachable: true
    gradient:
      points: []
  config:
    archetype: huelightstriptv
    function: mixed
    direction: omnidirectional
    startup:
      mode: safety
      configured: false
  protocol: homeassistant_ws
  protocol_cfg:
    entity_id: light.signify_netherlands_b_v_lcx003_light
    ip: none
```
there is only 1 light in your config.

**Comment by enoordam** [comment]
Right, why would there be more than 1? It's 1 lightstrip.

```
'1':
  id_v2: eeaf3ab9-2562-4328-a208-f15871c76fd7
  name: TV Ambient Lighting
  modelid: LST002
  uniqueid: 00:17:88:01:00:87:3a:7a-0b
  function: decorative
  state:
    'on': false
    bri: 254
    hue: 8417
    sat: 140
    effect: fire
    xy:
    - 0.193561
    - 0.067147
    ct: null
    alert: select
    colormode: xy
    mode: homeautomation
    reachable: true
    gradient:
      points: []
  config:
    archetype: huelightstrip
    function: decorative
    direction: omnidirectional
    startup:
      mode: safety
      configured: false
  protocol: homeassistant_ws
  protocol_cfg:
    entity_id: light.signify_netherlands_b_v_lcx003_light
    ip: none
```
