### ISSUE TITLE
Config files updated once every hour

### ISSUE THREAD

**Issue by TheFou** [diyhue/diyHue#1076]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

Hi,  

Not really a bug per se, but a bad practice to me.
Over the past two days of discovering and testing diyHue, I experimented with various settings and devices.
However, I couldn't understand why my changes were sometimes reflected in the configuration files and other times not... especially when I was trying to verify whether my modifications had actually been applied due to some odd behavior.

This also led to lost modifications whenever I restarted either diyHue itself or HAOS.
After some investigation, I finally realized that the configuration files are only updated once every hour, on the hour (1:00, 2:00, ...).

I later discovered the `Force Config Dump` option in the Bridge Control area, but honestly, it doesn’t make sense not to save the configuration immediately.
Configuration files should be updated as soon as a change is made to prevent any data loss.

That said, I’m unsure about automatically saving on app shutdown. At times, it's been necessary for me to restart the app to reload a manually modified configuration file. In that case, an automatic save would have overwritten those manual changes.

Perhaps you could add a **`Force Config Reload`** button in the Bridge Control area? Similar to how HA allows reloading its YAML files.
That would be a nice solution, and would mean the app saves automatically on shutdown, which would be a good practice.

Let me know your thoughts!
Regards.

### Errorlog:

N/A

### Steps to reproduce

N/A

### Please enter your operating system details here

Hue-Emulator Version: 2025-03-15 14:15:43.000000000
WebUI Version: 2025-03-15 14:15:45.000000000
Architecture: x86_64
OS: Linux
Linux version: #1 SMP PREEMPT_DYNAMIC Mon Mar 17 11:16:31 UTC 2025
Linux release: 6.12.18-haos

### Upload debug tar

N/A

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, thank you for the suggestion.
When i (or marius) will continue with the development of diyhue we will look into this.
Right now i (and marius) are very busy with other stuff.

**Comment by hendriksen-mark** [comment]
it is not recommend to manually change the config files, everything can be done in the webui and the hue app.
everything that is not changeable in the webui or hue app is not ment to be changed.
if you still want to manually change the config files you can enable advance options in the webui and restart python, this will reload the config files, be careful to not break anything.

**Comment by TheFou** [comment]
Yeah I try to avoid messing with config files.
Thanks for the suggestion, I didn't think about the Python restart reloading everything.

I edited the files to avoid losing some change, like for instance when lights were detected with the wrong type, but the change wasn't reflected in the files yet, and I needed to restart.
Or sometimes, when getting messed up things like this (the `lights` part) for instance, which happen quite a lot in various files :
```yaml
'10':
  id_v2: b9e5f832-628d-47bc-b1d7-58f64932fbfd
  name: Relax
  appdata: {}
  owner: 7b8a06c8021e11f0a409005056a689fe
  type: GroupScene
  picture: ''
  image: a1f7da49-d181-4328-abea-68c9dc4b5416
  recycle: false
  lastupdated: '2025-03-19T18:24:00'
  lights:
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  lightstates:
    '5':
      'on': true
      bri: 142
      ct: 447
    '6':
      'on': true
      bri: 142
      ct: 447
    '7':
      'on': true
      bri: 142
      ct: 447
    '8':
      'on': true
      bri: 142
      ct: 447
    '9':
      'on': true
      bri: 142
      ct: 447
    '10':
      'on': true
      bri: 142
      ct: 447
  group: '4'
  palette:
    color: []
    dimming: []
    color_temperature:
    - color_temperature:
        mirek: 447
      dimming:
        brightness: 56.25
    effects_v2: []
  speed: 0.603
```
