### ISSUE TITLE
Seeking insight on emulating dimmer switch functionality for z-wave hardware or alternatives

### ISSUE THREAD

**Issue by imbaimbaimba** [diyhue/diyHue#133]
Hi everyone,

I have been trying for a very long time by now, to make my Z-Wave connected wall switches work with Hue bulbs. Simply turning on/off is easy, but the issues quickly come when using scenes and with what I am currently working on; holdings buttons to change brightness. I am therefore looking for alternative ways and/or insight from people that are working deeply in the functionality/emulation.

So, my wall switches are:
-Logic Group ZHC5010 (4-button Z-Wave wall switch)
-Regular 1-2 button wall switches with Fibaro Double Switch 2 connected without any load. This is simply done to use the two inputs of the device to receive Z-Wave events when using the wall switch. 

The above might seem like an odd solution, but there are not many alternatives currently. I live in Denmark where we have very small (50x50mm) wall switch modules, and the only existing "smart" types are the ZHC5010 and the (unfortunately terrible) Niko Hue switches. 

I am trying to recreate the behavior of
- Fibaro Dimmer 2 for 1-button wall switches (Holding either brightens or dims the bulb depending on the current brightness level)
- Philips Hue Dimmer Switch for 2- and 4-button wall switches 

I currently have something that sort of works, but I am seeing a couple of issues:
-Constant rate of dimming. I don't know what the rate is for the Hue Dimmer Switch, but for Fibaro, the default is 100%(255) in 5 seconds. I tried to recreate this with a calculated value in Home Assistant, but I never got that working. 
-Lost inputs. Sometimes button pushes/holds are not registered for some reason. Might be down to a lot of things, but I assume the polling done from Home Assistant > deCONZ could be an issue. 
-Wrong direction of brightening. Sometimes the bulb will brighten on a hold, even though already very bright(far more than half, which is where I change the condition) Again, I think polling is the issue, as it does not have the correct value to evaluate the condition for what action to run.

I don't know if any of this could be solved by extending on the API calls, and not relying on any states in Home Assistant. If so, I do not know how to get there.

If anyone have any sort of insight, I would highly appreciate all the help I can get! I am very open to considering all sorts of ideas to get the functionality I am looking for, be it:
-Fixing the Home Assistant automations I have
-Implementing diyhue as part of my current setup to do some emulation (note, I have never used diyhue, so I currently know very little about it)
-Replacing my Z-Wave wall switches for something entirely different. I can (sort of) easily install more wires in my walls, so I could remove the ZHC5010 smart wall switches, and only use regular dumb wall switches, and wire them all to a central location. Would it be possible to have a hub that receives presses from these all through the house and achieve this kind of functionality this way? I did see the diyhue dimmer switch made from ESP8266, and was wondering if a bunch of these in a box could do it.

(A note about limitation; All my ZigBee devices are currently connected to my deCONZ server on the same mesh. This is because I have Hue bulbs spread across the house, which acts as routers for my Xiaomi sensors(used to provide data for my ventilation system automation)

Finally, here's what I currently have in my Home Assistant setup, and where I got stuck at completing it. The ???????? indicate missing calculation formula for transitiontime, but putting a static value there does make it work (well, with the quirks I mentioned)
```
rest_command:
  light1stop:
    url: 'http://myip:port/api/XXXXXXXXXX/lights/1/state'
    method: PUT
    headers:
      content-type: application/json
    payload: '{"bri_inc":0}'
  light1startup:
    url: 'http://myip:port/api/XXXXXXXXXX/lights/1/state'
    method: PUT
    headers:
      content-type: application/json
    payload: '{"on": true,
              "bri": 255,
              "transitiontime": "{{ transitiontimevariable }}"}'
  light1startdown:
    url: 'http://myip:port/api/XXXXXXXXXX/lights/1/state'
    method: PUT
    headers:
      content-type: application/json
    payload: '{"on": true,
              "bri": 1,
              "transitiontime": "{{ transitiontimevariable }}"}'
 
 automation:
    - alias: 'light1 - brighten'
    trigger:
    - event_data:
        entity_id: zwave.fibaro_system_fgs223_double_relay
        node_id: 24
        scene_id: 2
        scene_data: 2
        event_type: zwave.scene_activated
        platform: event
    condition:
        condition: or
        conditions:
        - condition: template
            value_template: '{{ states.light.light1.attributes.brightness < 157 }}'
    action:
      - service: rest_command.light1startup
        data:
          transitiontimevariable: !?!?!?!?!?

    - alias: 'light1 - dim'
    trigger:
    - event_data:
        entity_id: zwave.fibaro_system_fgs223_double_relay
        node_id: 24
        scene_id: 2
        scene_data: 2
        event_type: zwave.scene_activated
        platform: event
    condition:
        condition: or
        conditions:
        - condition: template
            value_template: '{{ states.light.light1.attributes.brightness > 157 }}'
    action:
      - service: rest_command.light1startdown
        data:
          transitiontimevariable: ???????????????????

    - alias: 'light1 - brighten'
    trigger:
    - event_data:
        entity_id: zwave.fibaro_system_fgs223_double_relay
        node_id: 24
        scene_id: 2
        scene_data: 1
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
      - service: rest_command.light1stop

    - alias: 'light1 - toggle'
    trigger:
    - event_data:
        entity_id: zwave.fibaro_system_fgs223_double_relay
        node_id: 24
        scene_id: 2
        scene_data: 0
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
        service: light.toggle
        entity_id: light.light1

    - alias: 'light1 - on full'
    trigger:
    - event_data:
        entity_id: zwave.fibaro_system_fgs223_double_relay
        node_id: 24
        scene_id: 2
        scene_data: 3
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
        service: light.turn_on
        entity_id: light.light1
        data_template:
        brightness: 255
```
