### ISSUE TITLE
Kubernetes yaml files

### ISSUE THREAD

**Issue by CyrosX** [diyhue/diyHue#790]
**Describe the issue**

Cannot get it working on Kubernetes.

**Steps you tried**

Tried creating deployment, service, persistentvolumeclaim.
Visit the IP:
404 page not found

**How we can help**

Correct my yaml files, please.

**Logs**

```
Host MAC given as #######
Docker Setup Initiated
SSL certificate found
Config file found
Docker Setup Complete
{"ok"}
{"ok"}
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 
Raspberry Pi 4 4GB, Raspbian, ARM, Latest Kubernetes & Latest image
**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: diyhue-claim0
  name: diyhue-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diyhue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: diyhue
  template:
    metadata:
      labels:
        run: diyhue
    spec:
      containers:
        - name: diyhue
          image: diyhue/core:latest
          env:
            - name: IP
              value: ####
            - name: MAC
              value: #####
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 1900
              protocol: UDP
            - containerPort: 2100
              protocol: UDP
            - containerPort: 1982
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /opt/hue-emulator/export
              name: diyhue-claim0
      restartPolicy: Always
      volumes:
        - name: diyhue-claim0
          persistentVolumeClaim:
            claimName: diyhue-claim0
status: {}
```
```
apiVersion: v1
kind: Service
metadata:
  name: diyhue
  labels:
    run: diyhue
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
  - port: 1900
    protocol: UDP
    targetPort: 1900
  - port: 2100
    protocol: UDP
    targetPort: 2100
  - port: 1982
    protocol: UDP
    targetPort: 1982
  selector:
    run: diyhue
```
